CREATE TABLE movies(
	id SMALLINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	full_name VARCHAR(50),
	film_title VARCHAR(50)
);

INSERT INTO movies
VALUES 
	(1,	'ALEC WAYNE',	'ALADDIN CALENDAR'),
    (2,	'BOB FAWCETT',	'ALADDIN CALENDAR'),
    (3	,'CHRISTIAN GABLE',	'ACADEMY DINOSAUR'),
    (4	,'DUSTIN TAUTOU',	'AFRICAN EGG'),
    (5	,'ELVIS MARX',	'ALABAMA DEVIL'),
    (6	,'FAY WINSLET',	'AFFAIR PREJUDICE');